services:
  postgres:
    container_name: ${CONTAINER_NAME}
    image: postgres:16-alpine
    environment:
       POSTGRES_PASSWORD: ${PG_PASS}
       POSTGRES_USER: ${PG_USER}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - ${PORT}:${PORT}